quarkus:
  application:
    name: pnc-repository-driver
  index-dependency:
    tracking-service:
      group-id: org.jboss.pnc
      artifact-id: pnc-api
      classifier: jakarta
  rest-client:
    tracking-service:
      url: ${repository-driver.tracking-service.api-url:http://localhost:8080}
      scope: jakarta.inject.Singleton
  otel:
    enabled: true
    traces:
      enabled: true
    exporter:
      otlp:
        # Send telemetry data to an opentelemetry-collector
        #endpoint: http://localhost:4317
  http:
    auth:
      # required for LDAP: build-time property
      basic: true
    enable-compression: true
    enable-decompression: true
    cors:
      enabled: true
      origins: "/.*/"
  security:
    ldap:
      # enable LDAP: build-time property
      enabled: true
      cache:
        enabled: true
        max-age: 5m
      dir-context:
        url: ldaps://ldap-server.com
      identity-mapping:
        search-base-dn: ou=company.com

  shutdown:
    timeout: 300
  log:
    category:
      "org.jboss.pnc":
        level: DEBUG
    console:
      format: "%d{HH:mm:ss,SSS} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{3.}] (%t) %s%e mdc:[%X]%n"
    handler:
      kafka:
        enabled: false
        broker-list: kafka.example.com:443
        topic: kafka-topic
        security-protocol: SSL
        ssl-truststore-location: /mnt/kafka-client-truststore.jks
        ssl-truststore-password: none
        filter-logger-name-pattern: org.jboss.pnc.*
        level: INFO
  oidc:
    auth-server-url: https://keycloak-host/auth/realms/myrealm
    client-id: client
    credentials:
      secret: secret
    tls:
      verification: none
  oidc-client:
    auth-server-url: http://localhost:8180/auth/realms/quarkus/
    client-id: my-app
    credentials:
      secret: secret

pnc_client_auth:
  type: OIDC # or LDAP
  # ldap_credentials:
  #    path: /mnt/secrets/ldap_credentials # file must be in format: <username>:<password>

repository-driver:
  backend: indy # indy or artifactory TO REMOVE
  deployment: prod # prod [pnc] / stage [pnc-stage] / devel [pnc-devel]
  ignored-path-patterns:
    archive:
      maven:
    promotion:
      maven:
      npm:
      generic:
    result:
      maven:
      npm:
      generic:
  ignored-repo-patterns:
    promotion:
    archive:
  temp-build-promotion-target:
  build-promotion-target:
  self-base-url:
  artifactory-client:
    url:
    accessToken:
  indy-client:
    api-url:
    request-timeout: 30
  indy-sidecar:
    enabled: false
    url:
  http-client:
    connect-timeout: 5lo
    request-timeout: 15
  callback-retry-duration: 600
  callback-retry-delay-msec: 500
  callback-retry-max-delay-msec: 5000
  archive-service:
    enabled: true
    api-url:
    prefer-http-2: true
    running-wait-for: 60
    running-retry-delay-msec: 500
    running-retry-max-delay-msec: 5000
  heartbeat:
    interval: 30
  tracking-service:
    api-url: http://localhost:8080
  repository:
    naming-structure: "{project}{type}{temporary}{build}{virtual}"
#    naming-structure: "{project}{temporary}{build}{virtual}{type}"
    # Previously in indy this was using e.g.
    # indy-{maven|npm}/api/content/maven/hosted/pnc-builds/....
    # https://indy.corp.redhat.com/api/content/maven/hosted/build-ASRETYOYGKQAA
    # or
    # indy-http/api/content/generic-http/hosted/
    # https://indy.corp.redhat.com/api/content/generic-http/hosted/g-repo-maven-apache-org-build-AQA6A6TJ4UQAG/maven2/org/eclipse/jgit/org.eclipse.jgit/maven-metadata.xml
    # https://indy.corp.redhat.com/api/content/generic-http/hosted/h-raw-githubusercontent-com-build-AND6P4MCDNQAA
    # or for remote
    # https://indy.corp.redhat.com/api/content/generic-http/remote/r-spdx-org-build-BH2PQ4DSFOIAQ
    # Artifactory layout will be different but not yet fully decided so rather than hard-coding, lets define it here
    #
    download-target-repository: "{project}{type}{url}"
    # https://indy.corp.redhat.com/api/content/maven/hosted/pnc-builds/com/datastax/oss/native-protocol/1.5.1.redhat-00001/native-protocol-1.5.1.redhat-00001.pom
    uploads-target-repository: "{project}{type}{target}"
