package org.jboss.pnc.repositorydriver.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.extern.jackson.Jacksonized;
import org.jboss.pnc.repositorydriver.Driver;

/**
 * @author <a href="mailto:matejonnet@gmail.com">Matej Lazar</a>
 */
@Getter
@AllArgsConstructor
@Jacksonized
@Builder(builderClassName = "Builder")
@JsonIgnoreProperties(ignoreUnknown = true)
public class CompleteRequest {

    /**
     * Used to destroy all the environments that were generated based on this label.
     */
    private String environmentLabel;

    /**
     * environmentId is generated by the {@link Driver#create(CreateRequest)} based on
     * {@link CreateRequest#getEnvironmentLabel()}
     */
    private String environmentId;

    private boolean enableDebug;

}
